services:
  varnish:
    network_mode: host
    container_name: tdwa.varnish
    image: darioguarascio/varnish-elk-docker:latest
    restart: unless-stopped
    volumes:
      - .config/varnish_backends.vcl:/usr/share/varnish/vcl/varnish_backends.vcl
    ports:
      - ${VARNISH_LISTEN:-80}:80
    environment:
      ENV: ${VARNISH_ENV:-dev}
      VARNISHD_MEMORY: ${VARNISH_MEMORY:-malloc,32m}
      VARNISH_PURGE_KEY: ${VARNISH_PURGE_KEY:-dev}
      VARNISH_PROJECT_CODE: ""
      VARNISH_RESTARTS_ON_ERROR: 0
    healthcheck:
      test: [ "CMD", "sh", "-c", "test -e /proc/`cat /varnish.pid` || (kill -s 15 -1 && (sleep 10; kill -s 9 -1))" ]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 5s
    logging:
      driver: syslog
      options:
        cache-disabled: "false"
        cache-max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        cache-max-file: ${DOCKER_LOG_MAX_FILE:-3}
        syslog-address: udp://${VARNISH_LOGGER_IP:-127.0.0.1}:${VARNISH_LOGGER_PORT:-5445}

  munin-node:
    image: darioguarascio/munin-node:latest
    container_name: tdwa.munin-node
    privileged: true
    restart: "always"
    environment:
      MUNIN_ALLOW: ${MUNIN_ALLOW:-0.0.0.0/0}
      MUNIN_ENABLED_PLUGINS: ${MUNIN_ENABLED_PLUGINS:-traffic cpu df netstat system* load memory uptime}
      MUNIN_LINKED_PLUGINS: ${MUNIN_LINKED_PLUGINS:-}
    volumes:
      - /tmp/munin-node:/data
    ports:
      - ${MUNIN_LISTEN:-127.0.0.1:4949}:4949
    env_file:
      - ${MUNIN_ENV_FILE:-.env}

    logging:
     options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}


  frontend:
    image: node:18
    container_name: tdwa.frontend
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      HOST: 0.0.0.0
    #   REDIS_URI: ${REDIS_URI:-redis://redis:6379}
    #   DB_HOST: ${DB_HOST:-postgresql}
    ports:
      - ${FRONTEND_LISTEN:-127.0.0.1:3000}:3000/tcp
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}
    command: node ./dist/server/entry.mjs
